version: '3.0'

services:
  searcher:
    container_name: "searcher_container"
    build: ./searcher
    restart: on-failure
    depends_on:
      - rabbit
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - ./searcher:/app
      - ./searcher/config.json:/app/config.json
      - errors:/resource/errors
      - analyzer:/resource/analyzer
      - search:/resource/search
    command: python3 main.py
  
  generator:
    container_name: generator_container
    build: ./generator
    depends_on:
      - searcher
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - ./generator:/app
      - ./generator/config.json:/app/config.json
      - search:/resource/search
    command: python3 loader.py

  analyzer:
    container_name: "analyzer_container"
    build: ./analyzer
    restart: on-failure
    depends_on:
      - searcher
      - mysql_database
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - ./analyzer:/app
      - ./analyzer/config.json:/app/config.json
      - analyzer:/resource/analyzer
    command: python3 main.py

  errors:
    container_name: "errors_container"
    build: ./erroneous
    restart: on-failure
    depends_on:
      - rabbit
      - searcher
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - ./erroneous:/app
      - ./erroneous/config.json:/app/config.json
      - errors:/resource/errors
    command: python3 main.py

  reader_sage:
    container_name: "reader_sage_container"
    build: ./reader_sage
    restart: on-failure
    depends_on:
      - generator
      - searcher
      - mysql_database
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - ./reader_sage:/app
    command: python3 main.py
    
  rabbit:
    image: rabbitmq:3.13.0-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  mysql_database:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=My7Pass@Word_9_8A_zE
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  search:
  errors:
  analyzer:
  mysql_data:
